### ISSUE TITLE
Execute Assembly not parsing arguments correctly

### ISSUE THREAD

**Issue by moscowchill** [chvancooten/NimPlant#21]
![image](https://github.com/chvancooten/NimPlant/assets/72578879/d5599033-0b84-4d89-b6ed-72b46dccc212)
When I run this it works fine without any additional quotes (could be the problem)
When I run this
![image](https://github.com/chvancooten/NimPlant/assets/72578879/799cd08a-d108-45ae-b9f6-db7b2b940a5d)
It somehow just prints the help menu of the tool without doing what I want.
Any idea?

**Comment by chvancooten** [comment]
Hi, thanks for reporting this. Could you please paste the exact command line for both versions? The first screenshot appears to be truncated.

**Comment by moscowchill** [comment]
The example working one:
SharPersist -t startupfolder -m list

A command that breaks/bugs execution:
execute-assembly C:\SharPersist.exe -t startupfolder -c "C:\Windows\System32\cmd.exe" -a "/c payload.exe" -f "Test File on Startup" -m add

**Comment by moscowchill** [comment]
ETW or AMSI did not seem to influence this behaviour.

**Comment by chvancooten** [comment]
Thanks for the additional information! It's very possible that the quotes break something, though I'm not exactly sure what would cause this behavior. Could you please try the following test cases and see if they improve anything? That may help pinpoint the issue?

- Use single quotes instead of double quotes
- Leaving out the quotes altogether
- Quote all arguments in single quotes, leaving the double quotes in place
- Escaping the quotes with a backslash (\)
