### ISSUE TITLE
Reg Command does not work

### ISSUE THREAD

**Issue by vysecurity** [chvancooten/NimPlant#6]
**Issue Description**

Reg command appears to not work:
![Brave Browser-2023-02-21 at 11 59 46@2x](https://user-images.githubusercontent.com/3596242/220244307-dd00eb09-2451-4f2c-981a-3043cefa1b6f.png)

Nor does: `reg query HKCU Software`

**Comment by chvancooten** [comment]
Have you tried escaping the backslashes? 

Also, please use the issue template best time 🙂

**Comment by vysecurity** [comment]
Yes tried escaping the \ with \\.

**Comment by chvancooten** [comment]
Thanks for the report. Was able to reproduce, and fixed in https://github.com/chvancooten/NimPlant/commit/91da37781b8422e3d68c5a9430aea192db5f2fea.
Ended up replacing the entire registry library since the Nim stdlib is quite lacking. Now the command properly supports enumerating all values in a certain key.

![image](https://user-images.githubusercontent.com/25614522/221366625-3b169c2b-fffd-49a9-b6bb-5a848414da56.png)

**Comment by vysecurity** [comment]
Fantastic!
